### PR TITLE
cylc-set-task.test1

### PR DESCRIPTION
**Pull request by wxtim**
@hjoliver  Request to add a broken test demonstating a possible bug.

Integration test version of:

```bash
mkdir -p ~/cylc-src/cylc-set-bugs/1
cd ~/cylc-src/cylc-set-bugs/1

cat > flow.cylc <<__ICI__
[scheduler]
    allow implicit tasks = true

[scheduling]
    [[graph]]
        R1 = """
            bar => baz
            bar:kustom? => baz
        """

[runtime]
    [[bar]]
        script = """
            sleep 300
            cylc message -- hi
        """
        [[[outputs]]]
            kustom = 'hi'
    [[baz]]
__ICI__


cylc vip

cylc set cylc-set-bugs/1//1/bar --out succeeded
cylc log cylc-set-bugs/1
```

### CODE REVIEW

**Comment by MetRonnie** [comment]
> ```shell
> cylc set cylc-set-bugs/1//1/foo --out suceeded
> ```

I presume you mean `bar` rather than `foo`? And `succeeded`

This doesn't seem to be related to `cylc set` though. This workflow stalls on master

```
[scheduler]
    allow implicit tasks = True
[scheduling]
    [[graph]]
        R1 = foo & foo:x? => bar
[runtime]
    [[foo]]
        script = true
        [[[outputs]]]
            x = x
```

**Comment by wxtim** [comment]
> This doesn't seem to be related to `cylc set` though. This workflow stalls on master

I guess that I should write this up as a bug on master. :(

**Comment by hjoliver** [comment]
See https://github.com/cylc/cylc-flow/pull/5658#issuecomment-1909776491

(In which case, it's more of a known bug that is about to be fixed as we finish off the optional outputs extension work)

**Comment by hjoliver** [comment]
On closer look, this example should stall!

The stall is caused by `bar` being partially satisfied, not by `foo` being incorrectly marked as incomplete.

**Pull request closed without merging**
