### PR TITLE
Xtrig arg validate

### PR DESCRIPTION
**Pull request by wxtim**
Close #5448 

This is not just a bug-fix for the `wall_clock` xtrigger - I've gone for a generic approach:
 - if an xtrigger module has a function called `validate_config` it will be called at validation time, with the parsed args.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by hjoliver** [comment]
> +10,607 −3,022

Borked rebase?

**Comment by wxtim** [comment]
> > +10,607 −3,022
> 
> Borked rebase?

Rebase over a very, very old branch.

**Comment by wxtim** [comment]
> > +10,607 −3,022
> 
> Borked rebase?

@hjoliver  Might you rebase the base branch?

**Comment by hjoliver** [comment]
Rebased the parent.

**Comment by wxtim** [comment]
Stale, replaced by https://github.com/cylc/cylc-flow/pull/5955

**Pull request closed without merging**
